list: $/sfc/sitesforchurch/models/location/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\Location
title: Locationinfo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/locationinfo/update/:id'
