list: $/sfc/sitesforchurch/models/maininfo/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\MainInfo
title: MainInfo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/maininfo/update/:id'
