list: $/sfc/sitesforchurch/models/homeinfo/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\HomeInfo
title: Homepage
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/homepage/update/:id'
