list: $/sfc/sitesforchurch/models/gospelpage/gospelcolumns.yaml
modelClass: Sfc\Sitesforchurch\Models\GospelPage
title: Gospel
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/gospel/update/:id'
