list: $/sfc/sitesforchurch/models/service/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\Service
title: ServiceSchedule
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/serviceschedule/update/:id'
