list: $/sfc/sitesforchurch/models/contact/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\Contact
title: Contactinfo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/contactinfo/update/:id'
