list: $/sfc/sitesforchurch/models/ministryleader/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\MinistryLeader
title: Ministryleader
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/ministryleader/update/:id'
