list: $/sfc/sitesforchurch/models/missionsletter/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\Missionsletter
title: Letters
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/letters/update/:id'
