list: $/sfc/sitesforchurch/models/event/columns.yaml
modelClass: Sfc\Sitesforchurch\Models\Event
title: Events
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sitesforchurch/events/update/:id'
